### ISSUE TITLE
Replace switch with large checkbox

### ISSUE THREAD

**Issue by Nevon** [klarna/ui#119]
Currently the `Switch` works really poorly in mobile, since the natural behavior is to swipe on it in order to change its value, but it only works with clicks. In KCO, we previously removed the Switch and used our own custom checkbox component both in mobile and desktop because users found the switch confusing.

I would suggest that until we have a switch component that works as expected that has been user tested to be working, we replace it with just a large checkbox.

Thoughts?

**Comment by xaviervia** [comment]
Yes, I agree. Not only that, the current responsiveness of the checkbox is weird and confusing. If we really want to have a checkbox in desktop and a toggle in mobile (I stress _if_) then we can just swap the components on a breakpoint.

@hannah-ahl @zenona ? Just in case you were not up to speed BTW, we actually are using the checkbox _always_ in the CAF because of what user testing revealed about the Switch.Toggle without swipe support.

**Comment by Nevon** [comment]
> Just in case you were not up to speed BTW, we actually are using the checkbox always in the CAF because of what user testing revealed about the Switch.Toggle without swipe support.

That's not exactly true. In production we are, but in develop we recently converted the entire CAF to use the ui components instead of our own cowboy components, which re-introduced this nasty behavior.

**Comment by Nevon** [comment]
We have a switch now, but it doesn't make this bug obsolete. We can't use the switch in every context, due to history gestures screwing things up, so we still need a mobile version of the checkbox.

**Comment by xaviervia** [comment]
👍 and it's a different component from many points of view, so we should have this.
