### ISSUE TITLE
Installments receive focus styling on touch

### ISSUE THREAD

**Issue by Nevon** [klarna/ui#156]
When scrolling in iOS 8 or 9, the installment options receive focus when touched, and retain it after the touch ends.

To reproduce, go to the showroom and scroll down, making sure that you touch one of the installment options as you do so. The option won't be selected, but the "hover" will be sticky.

**Comment by xaviervia** [comment]
This is the browser default behaviour for `:hover` states (it’s actually getting hover, not focus, they just look the same 😅). We might of course want to remove it. I’m personally torn. I guess we can make the `:hover` state more custom for the touch version.

**Comment by hannah-ahl** [comment]
(We’re working on separating the hover and focus for all types of elements from the toolkit team’s side, but it’s currently in the backlog due to more urgent issues)
Hannah Ahl
Product Designer
Product
+46 700 029 449 <tel:+46+700+029+449>
Klarna AB
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <tel:+46812012000>
Reg no: 556737-0431
klarna.co <http://klarna.com/>m

**Comment by Nevon** [comment]
Well, we should have hover, of course, but the problem is the "stickiness".

**Comment by xaviervia** [comment]
Hover is sticky in mobile, that's what I mean :D . `:hover` states are kind of a fake focus on mobile.

**Comment by xaviervia** [comment]
As long as we use `:hover` in CSS, it will be sticky on mobile. We would have to do some trick to make it behave differently if we want it not to do that (and I don’t know exactly how that’ll be).

**Comment by xaviervia** [comment]
Oh I see :D #158

**Comment by Nevon** [comment]
We worked around it by handling focus manually instead. Works like a charm!

**Comment by xaviervia** [comment]
I guess we can close this one then?
