### ISSUE TITLE
Add legal variation of Link

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui#80]
It should:

- Look "legal" gray
- Have underline by default (what is the hover effect)

**Comment by Nevon** [comment]
We need this for the account sign up in KCO (and presumably KC). @hannah-ahl, could we get some input on the hover state?

**Comment by hannah-ahl** [comment]
For the KCI API DE PAD (try saying that quickly 3 times) version we added the 20% #000 approach,
but for for corner cases (UK market) where we need to have the legal text in toolkit-black instead of toolkit-grey the hover isn’t visible until around ~80%
Hannah Ahl
Product Designer
Product
+46 700 029 449 <tel:+46+700+029+449>
Klarna AB
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <tel:+46812012000>
Reg no: 556737-0431
klarna.co <http://klarna.com/>m

**Comment by hannah-ahl** [comment]
Correction: 60, not 80
Hannah Ahl
Product Designer
Product
+46 700 029 449 <tel:+46+700+029+449>
Klarna AB
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <tel:+46812012000>
Reg no: 556737-0431
klarna.co <http://klarna.com/>m

**Comment by xaviervia** [comment]
Continues in =) https://github.com/klarna/ui/pull/122
