### ISSUE TITLE
Provide a built version

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui#81]
If possible, this would significantly simplify consumption since a webpack/babel built tool would not be necessary. It would enable the possibility of providing thin wrappers for other frameworks.

**Comment by JoakimLofgren** [comment]
I would love to try the UI toolkit with [Reagent](https://reagent-project.github.io/) (ClojureScript wrapper for React).

That would probably be easiest if we had it on [CLJSJS](http://cljsjs.github.io/).

Otherwise the approach to use external libraries is described here:
https://github.com/clojure/clojurescript/wiki/Dependencies#bundling-foreign-javascript-code

**Comment by xaviervia** [comment]
Continues in #120
