### ISSUE TITLE
Add a Button-as-a-Link variation of the Button

### ISSUE THREAD

**Issue by xaviervia** [klarna/ui#84]
So, some links need to look exactly like Buttons. Case in point, the "Get in touch" link at the bottom right of the Showroom. We need to provide a variation that supports href and so on.

**Comment by hannah-ahl** [comment]
I didn’t even think of that - does it make more sense to change it to a link instead of a button-as-a-link in the design?
Hannah Ahl
Product Designer
Product
+46 700 029 449 <tel:+46+700+029+449>
Klarna AB
Sveavägen 46, 111 34 Stockholm
Tel: +46 8 120 120 00 <tel:+46812012000>
Reg no: 556737-0431
klarna.co <http://klarna.com/>m

**Comment by xaviervia** [comment]
I think so. It is after all not a button at all: it's just a link that happens to _look like_ a Button.

**Comment by xaviervia** [comment]
Done
